# 路由
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:  # ===================================== 路由配置 start
        - id: test01
          uri: http://www.baidu.com
          predicates:
            - Path=/abc
          filters:
            - StripPrefix=1
        - id: settlement-service
          uri: lb://settlement-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: rrskx-service
          uri: lb://rrskx-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: azjf-service
          uri: lb://azjf-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: mecv-webservice
          uri: lb://mecv-webservice
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: aliyun_route
          uri: https://www.aliyun.com/
          predicates:
            - Path=/product/**
        - id: httpbin_route
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin/(?<segment>.*), /$\{segment}
      # ============================================= 路由配置 end
    nacos:
      discovery:
        server-addr: 101.201.235.188:8848
        namespace: 02c04789-0e01-49f8-adf8-b921bbeaaee6

# ===================================================================
# Application specific properties
# ===================================================================
